package org.whole.examples.datatypes;

import org.whole.lang.builders.IBuilderOperation;
import org.whole.lang.templates.AbstractTemplateFactory;

public class RedBlackTreeModel extends AbstractTemplateFactory<org.whole.lang.models.model.Model> {

    public void apply(IBuilderOperation op) {
        org.whole.lang.models.builders.IModelsBuilder b0 = (org.whole.lang.models.builders.IModelsBuilder) op.wGetBuilder(org.whole.lang.models.reflect.ModelsLanguageKit.URI);
        b0.Model_();
        b0.SimpleName("RedBlackTree");
        b0.TypeRelations_(0);
        b0._TypeRelations();
        b0.ModelDeclarations_(3);
        b0.SimpleEntity_();
        b0.EntityModifiers_(0);
        b0._EntityModifiers();
        b0.SimpleName("RBNode");
        b0.Types_(0);
        b0._Types();
        b0.Features_(4);
        b0.Feature_();
        b0.FeatureModifiers_(0);
        b0._FeatureModifiers();
        b0.SimpleName("Value");
        b0.SimpleName("value");
        org.whole.lang.commons.builders.ICommonsBuilder b1 = (org.whole.lang.commons.builders.ICommonsBuilder) op.wGetBuilder(org.whole.lang.commons.reflect.CommonsLanguageKit.URI);
        b1.Resolver();
        b0._Feature();
        b0.Feature_();
        b0.FeatureModifiers_(0);
        b0._FeatureModifiers();
        b0.SimpleName("Color");
        b0.SimpleName("color");
        b1.Resolver();
        b0._Feature();
        b0.Feature_();
        b0.FeatureModifiers_(1);
        b0.FeatureModifier("optional");
        b0._FeatureModifiers();
        b0.SimpleName("RBNode");
        b0.SimpleName("left");
        b1.Resolver();
        b0._Feature();
        b0.Feature_();
        b0.FeatureModifiers_(1);
        b0.FeatureModifier("optional");
        b0._FeatureModifiers();
        b0.SimpleName("RBNode");
        b0.SimpleName("right");
        b1.Resolver();
        b0._Feature();
        b0._Features();
        b0._SimpleEntity();
        b0.DataEntity_();
        b0.EntityModifiers_(0);
        b0._EntityModifiers();
        b0.SimpleName("Value");
        b0.Types_(0);
        b0._Types();
        b0.DataType("int");
        b0._DataEntity();
        b0.EnumEntity_();
        b0.EntityModifiers_(0);
        b0._EntityModifiers();
        b0.SimpleName("Color");
        b0.Types_(0);
        b0._Types();
        b0.EnumValues_(2);
        b0.EnumValue("BLACK");
        b0.EnumValue("RED");
        b0._EnumValues();
        b0._EnumEntity();
        b0._ModelDeclarations();
        b0.Namespace("org.whole.examples.datatypes.redblacktree");
        b1.Resolver();
        b0.URI("http://datatypes.examples.whole.org/RedBlackTree");
        b0._Model();
    }
}
