package org.whole.examples.dataintegration.motogp;

import org.whole.lang.builders.IBuilderOperation;
import org.whole.lang.templates.AbstractTemplateFactory;

public class MotoGP_TeamsFLFGrammar extends AbstractTemplateFactory<org.whole.lang.grammars.model.Grammar> {

    public void apply(IBuilderOperation op) {
        org.whole.lang.grammars.builders.IGrammarsBuilder b0 = (org.whole.lang.grammars.builders.IGrammarsBuilder) op.wGetBuilder(org.whole.lang.grammars.reflect.GrammarsLanguageKit.URI);
        b0.Grammar_();
        b0.Name("MotoGP_TeamsFLFGrammar");
        b0.LanguageDescriptor_();
        b0.URI("http://dataintegration.examples.whole.org/MotoGP");
        b0.Namespace("org.whole.examples.dataintegration.motogp");
        b0.Name("MotoGP");
        org.whole.lang.commons.builders.ICommonsBuilder b1 = (org.whole.lang.commons.builders.ICommonsBuilder) op.wGetBuilder(org.whole.lang.commons.reflect.CommonsLanguageKit.URI);
        b1.Resolver();
        b0._LanguageDescriptor();
        b0.NonTerminal("Teams");
        b1.Resolver();
        b0.Productions_(0);
        b0._Productions();
        b0.Productions_(4);
        b0.Production_();
        b0.NonTerminal("Teams");
        b0.Repeat_();
        b0.Size(2);
        b0.Unbounded();
        b1.Resolver();
        b0.Production_();
        b0.NonTerminal("Team");
        b0.Split_();
        b0.BySize(100);
        b0.Concatenate_(4);
        b0.Split_();
        b0.BySize(30);
        b0.As_();
        b0.NonTerminal("Name");
        b0.Name("name");
        b0._As();
        b0._Split();
        b0.Split_();
        b0.BySize(10);
        b0.As_();
        b0.NonTerminal("Name");
        b0.Name("manufacturer");
        b0._As();
        b0._Split();
        b0.As_();
        b0.NonTerminal("Rider");
        b0.Name("rider1");
        b0._As();
        b0.As_();
        b0.NonTerminal("Rider");
        b0.Name("rider2");
        b0._As();
        b0._Concatenate();
        b0._Split();
        b1.Resolver();
        b0._Production();
        b0._Repeat();
        b1.Resolver();
        b0._Production();
        b0.Production_();
        b0.NonTerminal("Rider");
        b0.Concatenate_(2);
        b0.Split_();
        b0.BySize(28);
        b0.As_();
        b0.NonTerminal("Name");
        b0.Name("name");
        b0._As();
        b0._Split();
        b0.Split_();
        b0.BySize(2);
        b0.As_();
        b0.NonTerminal("Number");
        b0.Name("number");
        b0._As();
        b0._Split();
        b0._Concatenate();
        b1.Resolver();
        b0._Production();
        b0.Production_();
        b0.NonTerminal("Name");
        b0.DataTerminal_();
        b0.RegExp("(([ ]?[a-zA-Z0-9]+)*)[ ]*");
        b0.Category("LITERAL");
        b0.Format("%s");
        b0._DataTerminal();
        b0.DataType("STRING");
        b0._Production();
        b0.Production_();
        b0.NonTerminal("Number");
        b0.DataTerminal_();
        b0.RegExp("[0-9]+");
        b0.Category("LITERAL");
        b0.Format("%02d");
        b0._DataTerminal();
        b0.DataType("INT");
        b0._Production();
        b0._Productions();
        b0.URI("http://dataintegration.examples.whole.org/MotoGP_TeamsFLFGrammar");
        b0.Namespace("org.whole.examples.dataintegration.motogp.grammars");
        b1.Resolver();
        b0._Grammar();
    }
}
